# Generated by Django 3.2.5 on 2021-10-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='is closed'),
        ),
    ]
