# Generated by Django 3.2.5 on 2021-10-27 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_requests', '0001_initial'),
        ('system_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepartrequest',
            name='maintenance_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maintenance_requests.maintenancerequest', verbose_name='Maintenace request'),
        ),
    ]
