# Generated by Django 3.2.5 on 2021-10-27 18:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('system_requests', '0002_sparepartrequest_maintenance_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepartrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 10, 27, 18, 9, 3, 210277, tzinfo=utc), verbose_name='Created at'),
            preserve_default=False,
        ),
    ]
