# Generated by Django 3.2.5 on 2021-10-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_requests', '0005_changemaintenancerequestdevicestatus_is_proceeded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changemaintenancerequestdevicestatus',
            name='status',
        ),
        migrations.AddField(
            model_name='changemaintenancerequestdevicestatus',
            name='requested_status',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Requested status'),
        ),
    ]
