# Generated by Django 3.2.5 on 2021-11-05 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientdevice'),
        ('storage', '0007_rename_ppt_item_ppu'),
        ('system_requests', '0007_auto_20211030_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(verbose_name='QTY')),
                ('total', models.FloatField(verbose_name='Total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Client')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Supply request',
                'verbose_name_plural': 'Supply requests',
            },
        ),
    ]
