# Generated by Django 3.2.5 on 2021-11-06 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance_requests', '0002_maintenancerequest_is_closed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system_requests', '0008_supplyrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(verbose_name='Action')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Action by')),
            ],
            options={
                'verbose_name': 'System log',
                'verbose_name_plural': 'System logs',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(verbose_name='Action')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Action by')),
                ('maintenance_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance_requests.maintenancerequest', verbose_name='Maintenace request')),
            ],
            options={
                'verbose_name': 'Maintenace request log',
                'verbose_name_plural': 'Maintenace request logs',
            },
        ),
    ]
