# Generated by Django 3.2.5 on 2021-10-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=350, verbose_name='Client name')),
                ('address', models.CharField(max_length=350, verbose_name='Address')),
                ('phone_number_1', models.CharField(max_length=350, verbose_name='Phone number 1')),
                ('phone_number_2', models.CharField(blank=True, max_length=350, null=True, verbose_name='Phone number 2')),
                ('fax', models.CharField(blank=True, max_length=350, null=True, verbose_name='Fax')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
