# Generated by Django 3.2.5 on 2021-10-15 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouse',
            old_name='name',
            new_name='warehouse_name',
        ),
    ]
