# Generated by Django 3.2.5 on 2021-10-16 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
        ('storage', '0003_warehouse_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=350, verbose_name='Item name')),
                ('item_img', models.ImageField(blank=True, null=True, upload_to='uploads/items_uploads', verbose_name='Item image')),
                ('qty', models.IntegerField(verbose_name='QTY')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.itemcategory', verbose_name='Category')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
    ]
