# Generated by Django 3.2.5 on 2021-11-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_auto_20211104_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='cash_drawer',
            field=models.FloatField(default=0.0, verbose_name='Cash drawer'),
        ),
    ]
