# Generated by Django 3.2.5 on 2021-11-04 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_alter_warehouse_cash_drawer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='ppt',
            new_name='ppu',
        ),
    ]
